### ISSUE TITLE
Docs are 404

### ISSUE THREAD

**Issue by davej** [sholladay/os-proxy#1]
URL in readme: https://sholladay.github.io/os-proxy

**Comment by sholladay** [comment]
This is due to some overly eager scaffolding tooling I am using. Would love some help on this. Otherwise, I am inclined to just remove the dead link until I have more time to write some decent docs. Will go ahead and do that before publishing to npm this week (see #2) unless someone is willing to chip in.

**Comment by sholladay** [comment]
Published `0.2.1` without that broken link. Will explore better docs as time allows.

**Comment by sholladay** [comment]
Finally got around to improving the API docs in https://github.com/sholladay/os-proxy/commit/298a36fbc932d253d24fc70eeec615d1a0e8cf05. 😃
